
name: test-python
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: env
      run: |
        echo "ROOT=$PWD" >> $GITHUB_ENV
    
    - run: $ROOT/script/test-python.sh