name: test-python
env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install python build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev wget curl llvm

      - name: install python
        run: |
          curl -s -S -L https://pyenv.run | bash

          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"

          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: set default python version
        run: |
          PY2_PATH="$HOME/.pyenv/versions/2.7.18/bin/python"
          sudo update-alternatives --install /usr/bin/python python $PY2_PATH 100
          sudo update-alternatives --set python $PY2_PATH

      - name: check python
        run: |
          python --version
