name: test-python
env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install python
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          curl -s -S -L https://pyenv.run | bash

          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"

          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: check python
        run: |
          python --version
          which python
