name: test-python
env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install python
        run: |
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
          source ~/.bashrc
          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: check python
        run: |
          python --version
          which python
