name: test-python
env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install python
        run: |
          sudo apt-get update
          apt-get search python2
          sudo apt-get install -y python2-minimal

      - name: check python
        run: |
          python --version
          which python
          python2 --version
          which python2